fixed served directories with index.html
joakimunge/denoliver pull request #22
Opened 2020-08-27 22:22 UTC by oscarotero

Hi, I have a directory with pretty urls, so requesting for urls such `/about-me/`, it should serve  the file `/about-me/index.html`. This does no work in v2.0, so made this change to fix it.

2020-08-28 07:26 UTC, joakimunge commented
> Hi, I have a directory with pretty urls, so requesting for urls such `/about-me/`, it should serve the file `/about-me/index.html`. This does no work in v2.0, so made this change to fix it.

Hi @oscarotero , and thank you very much for submitting this PR.

It appears a test is failing on this branch. Make sure all tests are passing, and also add a test case that covers this case. That would be great.

👍

2020-08-28 07:35 UTC, joakimunge requested changes

2020-08-28 07:35 UTC, joakimunge commented on mod.ts
> +    const file = await readFile(`${root}${req.url}${entryPoint}`)
I think this will break SPA functionality, no?

If your `root` is for example `/app`, and you request `/app/some-route/`, it will look for  `/app/some-route/index.html` which doesn't exist since it is still in `/app/index.html`

2020-08-28 11:19 UTC, oscarotero commented on mod.ts
> +    const file = await readFile(`${root}${req.url}${entryPoint}`)
Mmm, ok I didn't understand the purpose of `entryPoint`, because by default is `index.html`. Maybe we need an option to decide the router behaviour. Somethink like `spa: false` (so it will work as a simple static file server, but resolving paths to directories appending "index.hml" or `spa: "/app.html"` (so any not found request will resolve to the "app.html" file (or any other that's configured)

2020-08-31 11:03 UTC, joakimunge commented on mod.ts
> +    const file = await readFile(`${root}${req.url}${entryPoint}`)
Oh my, I just realized that I had not included the directory listing / static file server documentation in the readme.

Denoliver has something similar `denoliver -l` which disables routing and resolves paths to directories instead.

Have you tried that out? I will update the readme. Thanks for pointing it out

2020-08-31 16:41 UTC, oscarotero commented on mod.ts
> +    const file = await readFile(`${root}${req.url}${entryPoint}`)
Ok, that works better but does not fix the whole problem. In my opinion, if a directory contains an index.html file, it shouldn't list the files, but show this file, the same behaviour as any webserver. Can this behaviour be changed? Or provide an option for that?

2020-08-31 16:45 UTC, oscarotero commented on mod.ts
> +    const file = await readFile(`${root}${req.url}${entryPoint}`)
Another issue I found (not related with this one) is that BrokenPipe error appears randomly:

<img width="620" alt="imaxe" src="https://user-images.githubusercontent.com/377873/91744421-c8e2b800-ebb9-11ea-9a63-8fc06a548a05.png">

This is due `req.respond()` is an async function, so it should be prepended with an `await`, so the error can be catched:

```js
try {
   await req.respond({...});
catch (err) {
    //ignore error
}

2020-09-01 06:37 UTC, joakimunge commented on mod.ts
> +    const file = await readFile(`${root}${req.url}${entryPoint}`)
Ah, now I see what you mean. Sorry about that. No, that is definitely not intented behaviour. index files should be served if they exist.

Regarding the other issue, feel free to open a PR. Otherwise I will get to it soon

2025-03-11 10:36 UTC, oscarotero commented
I'm doing some cleanup on my old pull requests, closing this.
Thanks!

2025-03-11 10:36 UTC, closed without merging