support Windows
joakimunge/denoliver pull request #26
Opened 2020-08-31 14:35 UTC by korki43

What i did to support windows: 
 - catch the errors that a not existing dir causes and serve the 404 site instead
 - use windows command `ipconfig` to detect the local ip.

I tested it on my windows 10 machine.

2020-09-15 17:05 UTC, korki43 commented
Will this be reviewed or merged in the near future? I heard no feedback.

2020-09-16 05:52 UTC, joakimunge commented
> Will this be reviewed or merged in the near future? I heard no feedback.

Hi, currently I'm a bit busy with my full time job and other engagements, but will get to an actual review as soon as I can.

Thanks for submitting!

2020-09-19 14:03 UTC, korki43 commented
ok, thanks 😄

2020-10-06 08:01 UTC, joakimunge requested changes
Hi. Sorry for the late review. I have been very busy this last month. 

Great job on this. I added some minor comments. I would also ask you to introduce a Github Action workflow that runs the tests in a Windows Container to make sure the tests pass for windows as well.

Otherwise I can do that when I get the chance :)

2020-10-12 08:38 UTC, korki43 commented
I added a commit to remove the redundant code and opened #29 which introduces the CI workflow. I will also open a PR in [joakimunge/deno-local-ip](https://github.com/joakimunge/deno-local-ip) to synchronize the changes I made here.

2021-02-19 14:45 UTC, joakimunge requested changes
First of all thank you again for working on this. I am sorry for the late comments. Very busy, hope you understand! 

I have some minor things I would like to adress before merging

2021-02-19 14:45 UTC, joakimunge commented on mod.ts
> +        if (Deno.build.os == 'windows') path = 'file://'.concat(path)
I try to keep `var` and `let` out of the code whenever possible, and avoid mutation. I would suggest this approach instead.

```suggestion
        const path = Deno.build.os === "windows" ? 'file://'.concat(path) : resolve(`${root}/${args.after}`)
```

2021-02-19 14:45 UTC, joakimunge commented on utils/local-ip.ts
> +    let ifconfig = await Deno.run({
Could do `const` here!

2021-02-20 10:54 UTC, korki43 commented
I fully understand your points regarding the code style, but I'm currently unable to fix them as I unfortunately deleted my fork of your repo a while ago. I can't restore it via the "deleted Repos" tab, and I don't know another way to restore this branch to edit the code.

I think the repository owner is able to edit PRs. If this doesn't work, you could merge this PR and I (or you) would open a new PR to fix the code style issues. I also could close this PR and open a new one which will adress all the problems at once.

I'm really sorry for the inconvenience, I probably thougt this PR was closed when I deleted my fork.

2021-02-20 17:01 UTC, joakimunge commented
> I fully understand your points regarding the code style, but I'm currently unable to fix them as I unfortunately deleted my fork of your repo a while ago. I can't restore it via the "deleted Repos" tab, and I don't know another way to restore this branch to edit the code.
> 
> I think the repository owner is able to edit PRs. If this doesn't work, you could merge this PR and I (or you) would open a new PR to fix the code style issues. I also could close this PR and open a new one which will adress all the problems at once.
> 
> I'm really sorry for the inconvenience, I probably thougt this PR was closed when I deleted my fork.

That's a shame! I will see what I can do to implement your changes without having you or me redo all the changes you have made. Thanks for the work on this!

2021-03-19 12:12 UTC, korki43 commented
superseded by #35

2021-03-19 12:12 UTC, closed without merging